name: Build Maven Archetypes
on: push

jobs:
  build-enterprise-java-archetypes:
    runs-on: ubuntu-latest
    name: Build and Test Maven Archetypes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Maven projects
        run: ./buildArchetypes.sh

      - name: Verify Maven archetypes
        run: ./verifyArchetypes.sh

  build-basic-java-archetypes:
    runs-on: ubuntu-latest
    name: Build and Test Basic Maven Archetype
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Verify Archetype
        working-directory: testing-toolkit-archetype
        run: |
          ARCHETYPE_VERSION=$(./mvnw -q \
              -f "pom.xml" \
              -Dexec.executable=echo \
              -Dexec.args='${project.version}' \
              --non-recursive \
              exec:exec)

          ./mvnw install -Dgpg.skip

          mkdir tmp
          cd tmp

          ./mvnw archetype:generate \
            -DarchetypeGroupId=de.rieckpil.archetypes \
            -DarchetypeArtifactId=testing-toolkit \
            -DarchetypeVersion="$ARCHETYPE_VERSION" \
            -DgroupId=org.mycompany \
            -DartifactId=order-service \
            -DinteractiveMode=false

          cd order-service
          ./mvnw verify
